version: '3.9'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8089:80'
  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password   # Cambia esto por tu contraseña de root
      MYSQL_DATABASE: hotelselect          # Nombre de la base de datos que deseas crear
      MYSQL_USER: user                    # Nombre de usuario para acceder a la base de datos
      MYSQL_PASSWORD: password            # Contraseña del usuario
    ports:
      - "3307:3306"                       # Mapeo del puerto del contenedor al host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # Ruta al script SQL dentro del contenedor
    command: ['--init-file', '/docker-entrypoint-initdb.d/init.sql']
